### ISSUE TITLE
Behavior of isEmptyValue

### ISSUE THREAD

**Issue by keshavdv** [ajg/form#11]
The implementation of isEmptyValue makes encoding certain structs a bit non-intuitive. Similar to the discussion [here](http://stackoverflow.com/questions/38486564/golang-unmarshal-marshal-json-with-int-set-to-0-does-not-seem-to-work), I am trying to encode a 0 in a request.

I would expect the following code to result in "num=0&name=test" but instead I end up with "num=&name=test" even though my value does "exist".

```
package main

import (
	"bytes"
	"github.com/ajg/form"
	"log"
)

type Thing struct {
	String  string `form:"name,omitempty"`
	Integer *uint  `form:"num,omitempty"`
}

func main() {

	a_num := uint(0)
	u := Thing{"test", &a_num}
	buf := new(bytes.Buffer)
	if err := form.NewEncoder(buf).DelimitWith('|').Encode(u); err != nil {
		log.Printf("[ERR] %s", err)
	}
	body := buf.String()
	log.Printf("[DEBUG] %s", body)

}
```

**Comment by ajg** [comment]
@keshavdv, would offering an encoder option to disable encoding zero values (of types other than `string`) as the empty string solve your problem?

**Comment by ajg** [comment]
@keshavdv PR #12 implements the new functionality.
