### ISSUE TITLE
Feature Request: File uploads

### ISSUE THREAD

**Issue by CyrusJavan** [ajg/form#22]
It would be nice to have the ability to encode files in the form data.

For example, we could have a special struct tag that indicates this field represents a file path.

**Comment by matthewmueller** [comment]
Out of curiosity, how do you see this working @CyrusJavan?

Would it be something like this?

```go
type Input struct {
  Picture io.Reader `form:"picture"`
}
```

**Comment by CyrusJavan** [comment]
@matthewmueller I realize now that my issue is actually not with this encoding library but rather with the encoding itself. The API I was consuming required files to be multipart form encoded. 

Though what I was imaging was something like 
```
type Input struct {
  Picture string `form:"picture,_localfile”`
}
```

Where the `_localfile` tag would tell the library to look for this path to a file on disk.

**Comment by ajg** [comment]
For anyone who lands here: as of [v1.8.0](https://github.com/ajg/form/releases/tag/v1.8.0), the decode half of this request ships as a subpackage, github.com/ajg/form/multipart — struct fields of type *multipart.FileHeader / []*multipart.FileHeader (streamed) or []byte / [][]byte (read into memory, size-bounded) receive uploaded files, with value fields decoded by form's usual rules. The encode side — building multipart request bodies from structs, closer to what this issue originally asked for (including @matthewmueller's io.Reader idea) — isn't designed yet; if you have a live use case for it, a new issue with your desired API shape would genuinely influence what gets built.
