### ISSUE TITLE
Can decode/encode anonymous fields

### ISSUE THREAD

**Issue by dashaus** [ajg/form#3]
Hi!
In the app that I created found a problem. I use a lot of this library, it allow so much fields but not anonymous fields. For example, i have in my project a two structs:

```go
type Length struct {
    Title        map[string]string `json:"title"`
    Release  map[string]string `json:"release,omitempty"`
    Genres   Genre                  `json:"genres"`
    Topics    []string                 `json:"genres"`
}

type FilmBasedEpisodes struct {
    Length
    Channel  Channel
    Seasons  []Season
}
```
But when I want do this:

```go
....
r.ParseMultipartForm(maxMemory)
dataFormHTML := r.Form
film := FilmBasedEpisodes{}
err := form.DecodeValues(&film, dataFormHTML)
....
```

The content of ```dataFormHTML``` is, for example, like this: 
```javascript
"Title.US":"Six Feet Under", "Title.ES": "A dos metros bajo tierra", "Channel.Original":"HBO"
````

The error from ```ajg.form``` in go compiler is : **Title doesn't exist in struct main.FilmBasedEpisodes**

I understand that the library not is compatible with anonymous fields, right? If I wrong, then, how I do it?

Best,
Emilio

**Comment by ajg** [comment]
Hey @dashaus, sorry I couldn't investigate this earlier. Anyway, in [https://github.com/ajg/form/commit/3d986e16ddb00c1c8b040d377e3e35c7571c6038] I added support for unqualified embedded fields such that what I believe you want to do is now possible. Mind trying out the latest version and see if it works for you?
