### ISSUE TITLE
Intentional special casing of periods in form keys limits real-world usage

### ISSUE THREAD

**Issue by alienth** [ajg/form#9]
Due to the intentional special casing of periods within form, any API which uses periods in a form field cannot be interacted with without some hacks. For example, the fastly API utilizes periods in their form fields: https://docs.fastly.com/api/config#settings_9740ff4ac0c1777f455274c4850ece23

The `go-fastly` library attempted to work around this by manually ripping out the generated escapes, but that leads to other things being unintentionally ripped out, as noted in this case: https://github.com/sethvargo/go-fastly/issues/11

Is there any workaround for interacting with forms which have periods in their form keys?

**Comment by alienth** [comment]
Test case demonstrating the problem:

```
package main

import (
        "fmt"
        "github.com/ajg/form"
)

func main() {
        type test struct {
                Foo string `form:"general.default_ttl,omitempty"`
        }
        testing := test{Foo: "bar"}
        values, _ := form.EncodeToValues(testing)
        fmt.Println(values.Encode())
}
```

Output:
```
general%5C.default_ttl=bar
```

The addition of the backslash will not be accepted by the form recipient.

**Comment by ajg** [comment]
@alienth I opened a PR with support for custom delimiter & escape support (https://github.com/ajg/form/pull/10/files). So in your example, you'd be able to do e.g.:

```go
form.NewEncoder(os.Stdout).DelimitWith('/').Encode(testing)
```

Would that solve your problem?

**Comment by alienth** [comment]
@ajg Verified that using something like this will address my problem.

**Comment by ajg** [comment]
@alienth glad to hear it; will merge shortly.
